import type { Product } from '@/types';

// Mock products for development when backend is unavailable
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'FC Barcelona Home Kit 2025/26 - Pedri #8',
    nameAr: 'طقم برشلونة الأساسي 2025/26 - بيدري #8',
    description: 'Official FC Barcelona home kit with Pedri name and number.',
    descriptionAr: 'طقم برشلونة الأساسي الرسمي مع اسم ورقم بيدري.',
    club: 'FC Barcelona',
    clubAr: 'نادي برشلونة',
    player: 'Pedri',
    playerAr: 'بيدري',
    league: 'La Liga',
    leagueAr: 'الدوري الإسباني',
    season: '2025/26',
    kitType: 'home',
    category: 'full_kit',
    basePrice: 349,
    featured: true,
    createdAt: '2025-08-01',
    images: [
      { id: 'img1', url: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&h=600&fit=crop', alt: 'Barcelona Home Kit', isPrimary: true },
    ],
    variants: [
      { id: 'v1', productId: '1', size: 'S', stock: 10, price: 349 },
      { id: 'v2', productId: '1', size: 'M', stock: 15, price: 349 },
      { id: 'v3', productId: '1', size: 'L', stock: 8, price: 349 },
      { id: 'v4', productId: '1', size: 'XL', stock: 5, price: 349 },
    ],
  },
  {
    id: '2',
    name: 'Real Madrid Home Shirt 2025/26 - Vinícius Jr. #7',
    nameAr: 'قميص ريال مدريد الأساسي 2025/26 - فينيسيوس جونيور #7',
    description: 'Official Real Madrid home shirt with Vinícius Jr. name and number.',
    descriptionAr: 'قميص ريال مدريد الأساسي الرسمي مع اسم ورقم فينيسيوس.',
    club: 'Real Madrid',
    clubAr: 'ريال مدريد',
    player: 'Vinícius Jr.',
    playerAr: 'فينيسيوس جونيور',
    league: 'La Liga',
    leagueAr: 'الدوري الإسباني',
    season: '2025/26',
    kitType: 'home',
    category: 'shirt',
    basePrice: 279,
    featured: true,
    createdAt: '2025-08-10',
    images: [
      { id: 'img2', url: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=600&h=600&fit=crop', alt: 'Real Madrid Home Shirt', isPrimary: true },
    ],
    variants: [
      { id: 'v5', productId: '2', size: 'S', stock: 12, price: 279 },
      { id: 'v6', productId: '2', size: 'M', stock: 20, price: 279 },
      { id: 'v7', productId: '2', size: 'L', stock: 6, price: 279 },
      { id: 'v8', productId: '2', size: 'XL', stock: 3, price: 279 },
    ],
  },
  {
    id: '3',
    name: 'PSG Away Kit 2025/26 - Mbappé #7',
    nameAr: 'طقم باريس سان جيرمان الاحتياطي 2025/26 - مبابي #7',
    description: 'Official PSG away kit with Mbappé name and number.',
    descriptionAr: 'طقم باريس سان جيرمان الاحتياطي الرسمي مع اسم ورقم مبابي.',
    club: 'Paris Saint-Germain',
    clubAr: 'باريس سان جيرمان',
    player: 'Mbappé',
    playerAr: 'مبابي',
    league: 'Ligue 1',
    leagueAr: 'الدوري الفرنسي',
    season: '2025/26',
    kitType: 'away',
    category: 'full_kit',
    basePrice: 369,
    featured: true,
    createdAt: '2025-07-20',
    images: [
      { id: 'img3', url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=600&h=600&fit=crop', alt: 'PSG Away Kit', isPrimary: true },
    ],
    variants: [
      { id: 'v9', productId: '3', size: 'M', stock: 18, price: 369 },
      { id: 'v10', productId: '3', size: 'L', stock: 10, price: 369 },
      { id: 'v11', productId: '3', size: 'XL', stock: 7, price: 369 },
    ],
  },
  {
    id: '4',
    name: 'Manchester City Home Shirt 2025/26 - Haaland #9',
    nameAr: 'قميص مانشستر سيتي الأساسي 2025/26 - هالاند #9',
    description: 'Official Manchester City home shirt with Haaland name and number.',
    descriptionAr: 'قميص مانشستر سيتي الأساسي الرسمي مع اسم ورقم هالاند.',
    club: 'Manchester City',
    clubAr: 'مانشستر سيتي',
    player: 'Haaland',
    playerAr: 'هالاند',
    league: 'Premier League',
    leagueAr: 'الدوري الإنجليزي',
    season: '2025/26',
    kitType: 'home',
    category: 'shirt',
    basePrice: 289,
    featured: false,
    createdAt: '2025-09-01',
    images: [
      { id: 'img4', url: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?w=600&h=600&fit=crop', alt: 'Man City Home Shirt', isPrimary: true },
    ],
    variants: [
      { id: 'v12', productId: '4', size: 'S', stock: 5, price: 289 },
      { id: 'v13', productId: '4', size: 'M', stock: 11, price: 289 },
      { id: 'v14', productId: '4', size: 'L', stock: 9, price: 289 },
      { id: 'v15', productId: '4', size: 'XL', stock: 0, price: 289 },
    ],
  },
  {
    id: '5',
    name: 'Liverpool Third Kit 2025/26 - Salah #11',
    nameAr: 'الطقم الثالث ليفربول 2025/26 - صلاح #11',
    description: 'Official Liverpool third kit with Salah name and number.',
    descriptionAr: 'الطقم الثالث الرسمي لليفربول مع اسم ورقم صلاح.',
    club: 'Liverpool',
    clubAr: 'ليفربول',
    player: 'Salah',
    playerAr: 'صلاح',
    league: 'Premier League',
    leagueAr: 'الدوري الإنجليزي',
    season: '2025/26',
    kitType: 'third',
    category: 'full_kit',
    basePrice: 359,
    featured: true,
    createdAt: '2025-08-15',
    images: [
      { id: 'img5', url: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&h=600&fit=crop', alt: 'Liverpool Third Kit', isPrimary: true },
    ],
    variants: [
      { id: 'v16', productId: '5', size: 'S', stock: 7, price: 359 },
      { id: 'v17', productId: '5', size: 'M', stock: 14, price: 359 },
      { id: 'v18', productId: '5', size: 'L', stock: 11, price: 359 },
      { id: 'v19', productId: '5', size: 'XL', stock: 4, price: 359 },
      { id: 'v20', productId: '5', size: 'XXL', stock: 2, price: 359 },
    ],
  },
  {
    id: '6',
    name: 'Bayern Munich Away Shirt 2025/26 - Musiala #42',
    nameAr: 'قميص بايرن ميونخ الاحتياطي 2025/26 - موسيالا #42',
    description: 'Official Bayern Munich away shirt with Musiala name and number.',
    descriptionAr: 'قميص بايرن ميونخ الاحتياطي الرسمي مع اسم ورقم موسيالا.',
    club: 'Bayern Munich',
    clubAr: 'بايرن ميونخ',
    player: 'Musiala',
    playerAr: 'موسيالا',
    league: 'Bundesliga',
    leagueAr: 'الدوري الألماني',
    season: '2025/26',
    kitType: 'away',
    category: 'shirt',
    basePrice: 269,
    featured: false,
    createdAt: '2025-09-05',
    images: [
      { id: 'img6', url: 'https://images.unsplash.com/photo-1517466787929-bc90951d0974?w=600&h=600&fit=crop', alt: 'Bayern Away Shirt', isPrimary: true },
    ],
    variants: [
      { id: 'v21', productId: '6', size: 'M', stock: 9, price: 269 },
      { id: 'v22', productId: '6', size: 'L', stock: 13, price: 269 },
      { id: 'v23', productId: '6', size: 'XL', stock: 6, price: 269 },
    ],
  },
];
